import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Check, Copy, ExternalLink, ChevronDown, ChevronUp } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import type { ParlayWithLegs } from "@shared/schema";

interface Props {
  parlay: ParlayWithLegs;
  leagueName?: string;
}

const SPORTSBOOKS = [
  { name: "DraftKings",  url: "https://sportsbook.draftkings.com/",           color: "bg-[#1b5e20] hover:bg-[#2e7d32] text-white" },
  { name: "FanDuel",     url: "https://sportsbook.fanduel.com/",              color: "bg-[#1565c0] hover:bg-[#1976d2] text-white" },
  { name: "BetMGM",      url: "https://sports.betmgm.com/en/sports",          color: "bg-[#b71c1c] hover:bg-[#c62828] text-white" },
  { name: "Caesars",     url: "https://www.caesars.com/sportsbook-and-casino", color: "bg-[#7b5e00] hover:bg-[#a07c00] text-white" },
];

export function buildSlipText(parlay: ParlayWithLegs, leagueName?: string): string {
  const lines: string[] = [];

  const title = leagueName
    ? `PARLAY BET SLIP — ${parlay.week?.label ?? "Current Week"} | ${leagueName}`
    : `PARLAY BET SLIP — ${parlay.week?.label ?? "Current Week"}`;
  lines.push(title);
  lines.push("─".repeat(Math.min(title.length, 52)));

  parlay.legs.forEach((leg, i) => {
    const num = `Leg ${i + 1}`;
    const segment = (leg as any).gameSegment ? ` [${(leg as any).gameSegment}]` : "";

    if (leg.betType === "player_prop") {
      const player = leg.playerName || "Player";
      const propLabel = leg.propType
        ? leg.propType.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
        : "Prop";
      const pickPart = `${leg.pick.charAt(0).toUpperCase()}${leg.pick.slice(1)}${leg.line ? ` ${leg.line}` : ""}`;
      const oddsPart = (leg as any).odds ? ` (${(leg as any).odds})` : "";
      lines.push(`${num}: ${player} — ${propLabel}${segment}`);
      lines.push(`  Pick: ${pickPart}${oddsPart} [Player Prop]`);
    } else {
      const away = leg.game?.awayTeam ?? "Away";
      const home = leg.game?.homeTeam ?? "Home";
      const matchup = `${away} @ ${home}`;

      let pickText = "";
      const odds = (leg as any).odds;

      if (leg.betType === "over") {
        const total = leg.line || leg.game?.overUnder;
        pickText = `Over ${total}${odds ? ` (${odds})` : ""}`;
      } else if (leg.betType === "under") {
        const total = leg.line || leg.game?.overUnder;
        pickText = `Under ${total}${odds ? ` (${odds})` : ""}`;
      } else if (leg.betType === "moneyline") {
        const team = leg.pick === "home" ? home : away;
        pickText = `${team}${odds ? ` ${odds}` : ""} [Moneyline]`;
      } else {
        const team = leg.pick === "home" ? home : away;
        const line = leg.line || (leg.pick === "home" ? leg.game?.spread : undefined);
        pickText = `${team}${line ? ` ${line}` : ""}${odds ? ` (${odds})` : ""} [Spread]`;
      }

      const betLabel =
        leg.betType === "over" || leg.betType === "under" ? " [Total]" : "";

      lines.push(`${num}: ${matchup}${segment}`);
      lines.push(`  Pick: ${pickText}${betLabel}`);
    }
  });

  lines.push("─".repeat(36));
  lines.push("Generated by Parlayconch");

  return lines.join("\n");
}

export function BetSlipPanel({ parlay, leagueName }: Props) {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const slipText = buildSlipText(parlay, leagueName);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(slipText);
      setCopied(true);
      toast({ title: "Bet slip copied!", description: "Paste it into your sportsbook app." });
      setTimeout(() => setCopied(false), 2500);
    } catch {
      toast({ title: "Copy failed", description: "Please copy the text manually.", variant: "destructive" });
    }
  };

  return (
    <div className="mt-4 pt-4 border-t border-white/10 space-y-3">
      {/* Copy row */}
      <div className="flex items-center justify-between gap-3">
        <button
          onClick={() => setExpanded((v) => !v)}
          className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
        >
          {expanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
          {expanded ? "Hide slip" : "Preview slip"}
        </button>
        <Button size="sm" variant="outline" onClick={handleCopy} className="h-8 gap-1.5 text-xs">
          {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
          {copied ? "Copied!" : "Copy Bet Slip"}
        </Button>
      </div>

      {/* Expandable text preview */}
      {expanded && (
        <pre className="text-[11px] font-mono text-muted-foreground bg-black/30 rounded-xl border border-white/10 px-4 py-3 whitespace-pre-wrap leading-relaxed overflow-x-auto">
          {slipText}
        </pre>
      )}

      {/* Sportsbook launch row */}
      <div className="space-y-1.5">
        <p className="text-[10px] uppercase tracking-wider text-muted-foreground/60 font-medium">
          Open Sportsbook
        </p>
        <div className="flex flex-wrap gap-2">
          {SPORTSBOOKS.map((book) => (
            <a
              key={book.name}
              href={book.url}
              target="_blank"
              rel="noopener noreferrer"
              className={`inline-flex items-center gap-1 rounded-lg px-3 py-1.5 text-[11px] font-semibold transition-colors ${book.color}`}
            >
              {book.name}
              <ExternalLink className="w-2.5 h-2.5 opacity-70" />
            </a>
          ))}
        </div>
        <p className="text-[10px] text-muted-foreground/50 italic">
          Auto-staging picks in sportsbook apps is coming soon. Copy the slip above and paste it manually for now.
        </p>
      </div>
    </div>
  );
}
